### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by Akshay-Thakare** [HDFGroup/hsds#53]
Hi,

I was attempting to setup hsds on AWS k8s instance but for some odd reason the default password `admin:admin` does not seem to work even when set in `passwd.txt` file.

When trying to run `$ hsconfigure` it keeps giving the error `Unauthorized (username/password or api key not valid)`

My deployment yaml looks as follows (have some same for `dn` container too)
```
containers:
        -
          name: sn
          image: hdfgroup/hsds:latest
          ports:
          .....
          env:
          - name: HSDS_ENDPOINT
            value: http://localhost:5101
```

I did ssh into the `sn` container to check if the passwd.txt file was present and indeed it was.
I also created my own docker image with password file set as suggested in the document but with no luck.

Kindly let me know how to resolve this issue.

Thanks,
Akshay
